apiVersion: v1
kind: ConfigMap
metadata: 
  name: my-vars
data:
  DB_NAME: studentapp
  DB_USER: Anil
  DB_PASSWORD: "Redhat"

  ---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-vars
data:
  database_name: studentapp
  user_name: Anil
  db_password: redhat