apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
        - name: my-container
          image: httpd:latest
          ports:
            - containerPort: 80
   
