apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod-a
spec:
  containers:
  - name: tomacat
    image: tomcat
    ports:
    - name: tomcat
      containerPort: 8080
  - name: apache
    image:  httpd
    ports:
    - name: httpd
      containerPort: 80 

---
apiVersion: v1
kind : Pod 
metadata:
  name: my-pod
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
      - name: tomcat 
        containerPort: 8080
    - name: apache 
      image: httpd:latest
      ports:
      - name: httpd:latest
        containerPort: 80
