apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-secret
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: my-vars
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-sec
          key: DB_PASSWORD